### ISSUE TITLE
typescript не работает автодополнение

### ISSUE THREAD

**Issue by Bobrovskih** [sergeysova/telegram-typings#13]
не работает автодополнение
и появляется ошибка при попытке считать свойство ctx.message.from
[ts] Type 'Message | undefined' has no property 'from' and no string index signature.

![image](https://user-images.githubusercontent.com/34475297/39348974-e74693fe-4a01-11e8-9a82-8c80dce0ced1.png)

typescript 2.8.3
telegram-typings 3.6.0

**Comment by Piterden** [comment]
```js
const { from } = ctx;
```

**Comment by sergeysova** [comment]
@Bobrovskih судя по документации https://core.telegram.org/bots/api#message, поле `from` опциональное и его нужно проверять на `if (from) {`

а вот то, что там `Message` вместо `User`, я проверю. Спасибо

**Comment by Piterden** [comment]
Так а он `Message`'ю называет `ctx.message`, а не `from`...

```js
const message = ctx.message
  || ctx.edited_message
  || ctx.channel_post
  || ctx.edited_channel_post
  || ctx.inline_query
  || ctx.chosen_inline_result
  || ctx.callback_query
  || ctx.shipping_query
  || ctx.pre_checkout_query

const { from } = message
```

**Comment by sergeysova** [comment]
@Piterden автор вопроса юзает именно `ctx.message`

**Comment by Bobrovskih** [comment]
if (from) { ... } помогает, спасибо

**Comment by Piterden** [comment]
А покажи куда ты вставил условие, @Bobrovskih 
Чет я не вкурил...
