### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by valscion** [sergeysova/telegram-typings#14]
Hi!

I was just looking around whether anyone had created flowtype compatible types for Telegram Bot API and I stumbled upon this project.

It looks so amazing, and seems to work with the bot I'm currently writing!

Thank you for creating this :relaxed:. I'll see if I spot some strange cases with Flow and this package and see if I can contribute in any way

Have a great weekend!

**Comment by sergeysova** [comment]
Hi
Very pleasant! Thank you for contribution
