### ISSUE TITLE
Parse methods

### ISSUE THREAD

**Issue by sergeysova** [sergeysova/telegram-typings#2]
Methods has column named `Parameters`

Example: https://core.telegram.org/bots/api#answerinlinequery

Depends on #1

**Comment by valscion** [comment]
I think #18 fixed this issue, right? What's missing is proper output for methods. One possibility would be what @sergeysova said here: https://github.com/sergeysova/telegram-typings/pull/18#issuecomment-387486772

Working on this should not happen before the refactoring of builders, from classes to functions, if I understood this correctly: https://github.com/sergeysova/telegram-typings/pull/18#issuecomment-387512909
