### ISSUE TITLE
Parse links in description

### ISSUE THREAD

**Issue by sergeysova** [sergeysova/telegram-typings#4]
Links from description should be placed to comment into `@see` property.

Example: https://core.telegram.org/bots/api#forcereply

```js
/**
  * Upon receiving a message with this object,
  * Telegram clients will display a reply interface to the user
  * (act as if the user has selected the bot‘s message and tapped ’Reply').
  * This can be extremely useful if you want to create user-friendly step-by-step
  * interfaces without having to sacrifice privacy mode.
  * @see https://core.telegram.org/bots#privacy-mode
  */
export type ForceReply = {
}
```

**Comment by sergeysova** [comment]
```js
target.querySelectorAll('a').map(e => e.href)
```

**Comment by Piterden** [comment]
https://github.com/sergeysova/telegram-typings/commit/09163bbb830b9f55f1b0c92826aee2093207baa4

**Comment by Piterden** [comment]
So, what about a commit. Does it need to be redone?

Also, don't you think we should ignore those generated files from the repository and put their parts in the readme like examples?

**Comment by sergeysova** [comment]
Not. Files is needed when install package to project
